'use client'

import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header'
import Form from '@/components/Form'
import Footer from '@/components/Footer'

import { poppins } from '@/utils/Fonts'
import { orbitron } from '@/utils/Fonts'
import { cinzel } from "@/utils/Fonts";
import { josefin } from '@/utils/Fonts'
import { caveat } from '@/utils/Fonts'
import { great } from '@/utils/Fonts'
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "SURGING PHOENIX | ENTERPRISES",

//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [active, setActive] = useState(false)

  const handleToggle = () => {
    setActive(!active)
  }


  return (
    <html lang="en">
      <body className={`${poppins} ${orbitron} ${josefin} ${caveat} ${cinzel} ${great}`}>

        {
          active && <>
            <Form handleToggle={handleToggle} />
          </>
        }
        <Header handleToggle={handleToggle} />

        {children}

        {/* <Footer /> */}

      </body>
    </html >
  );
}
