import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header'
import Footer from '@/components/Footer'

import { poppins } from '@/utils/Fonts'
import { orbitron } from '@/utils/Fonts'
import { josefin } from '@/utils/Fonts'
import { caveat } from '@/utils/Fonts'

export const metadata: Metadata = {
  title: "Surging Phoenix Enterprises",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins} ${orbitron} ${josefin} ${caveat}`}>
        <Header />
        {children}
        {/* <Footer /> */}

      </body>
    </html>
  );
}
